# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'realmTest' do

pod "Realm"

end

target 'realmTestTests' do

end

